fixed "double rsync" logic

diff --git a/rpm-filenames b/rpm-filenames
--- a/rpm-filenames
+++ b/rpm-filenames
@@ -19,11 +19,21 @@ rc=
 
 for m in $mm; do
 	[ -s m/$m ] && continue
-	{ rsync1 $M::$m >m/.out ||
-	  rsync1 $M::$m >m/.put ||
-	  { [ -s m/.out ] && cmp -s m/.out m/.put; }; } &&
-		{ echo >&2 ok: $m; } ||
-		{ echo >&2 failed: $m; rc=1; continue; }
+	if ! rsync1 $M::$m >m/.out; then
+		if rsync1 $M::$m >m/.put; then
+			# second try succeeds
+			mv m/.put m/.out
+		elif [ -s m/.out ] && cmp -s m/.out m/.put; then
+			# second try fails in exactly the same way,
+			# with non-empty output, perhaps due to...
+			: permission denied on a bad dir
+		else
+			echo >&2 failed: $m
+			rc=1
+			continue
+		fi
+	fi
+	echo >&2 ok: $m
 	[ -s m/.out ] && mv m/.out m/$m
 done
 
